name: Lint repository
on: [push]

jobs:
  repo-lint-custom:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Setup repolinter
        run: npm i -g repolinter
      - name: List files
        run: |
          pwd
          ls -a
      - name: Lint repository
        run: repolinter lint
